ecommerce_homepage:
    path:     /
    defaults: { _controller: EcommerceBundle:Default:index }

categorie:
    path:     /categorie
    defaults: { _controller: EcommerceBundle:Categorie:index }
    
produit:
    path:     /categorie/produit
    defaults: { _controller: EcommerceBundle:Produit:index }